export {
  s3Client,
  DOCUMENTS_BUCKET,
  getDocument,
  getDocumentBuffer,
  getJsonDocument,
  listDocuments,
  getDocumentsIndex,
  getEntitiesFromS3,
  putDocument,
  putDocumentBinary,
  deleteDocument,
  updateDocumentsIndex,
  getSignedUrl,
  // Versioning
  listDocumentVersions,
  getDocumentVersion,
  getDocumentVersionBuffer,
  restoreDocumentVersion,
  getSignedUrlForVersion,
  getCurrentVersionId,
  // Types
  type DocumentMetadata,
  type S3Entity,
  type DocumentVersion,
  type LegalDocumentType,
  type DocumentReviewStatus,
} from "./client";
