export { docClient, dynamoClient } from "./client";
export * from "./tables";
export * from "./chat";
// Re-export entities selectively to avoid PaginatedResult conflict
export {
  listEntities,
  getEntity,
  createEntity,
  updateEntity,
  deleteEntity,
  batchCreateEntities,
  isEntitiesEmpty,
  getEntityMap,
} from "./entities";
export type {
  Entity,
  EntityType,
  EntityMetadata,
  CreateEntityInput,
  UpdateEntityInput,
  EntityMap,
} from "./entities";

// Documents sync status
export {
  getDocumentSyncStatus,
  getAllDocumentSyncStatuses,
  updateDocumentSyncStatus,
  deleteDocumentSyncStatus,
} from "./documents";
export type { DocumentSyncStatus } from "./documents";

// Notifications
export {
  createNotification,
  getNotifications,
  markNotificationAsRead,
  markAllNotificationsAsRead,
  deleteNotification,
  clearAllNotifications,
  getUnreadNotificationCount,
} from "./notifications";
export type {
  Notification,
  NotificationType,
  NotificationCategory,
  CreateNotificationInput,
} from "./notifications";

// Utilities
export {
  CONTENT_TYPE_MAP,
  BINARY_EXTENSIONS,
  getContentType,
  isBinaryFile,
  getFileExtension,
  generateDocumentId,
  sanitizeFilename,
  generateDocumentPath,
  estimatePageCount,
} from "./utilities";

// S3 Document Operations (re-export from s3 submodule)
export {
  getDocumentsIndex,
  getDocument,
  getDocumentBuffer,
  putDocument,
  putDocumentBinary,
  deleteDocument,
  updateDocumentsIndex,
  getSignedUrl,
  // Versioning
  listDocumentVersions,
  getDocumentVersion,
  getDocumentVersionBuffer,
  restoreDocumentVersion,
  getSignedUrlForVersion,
  getCurrentVersionId,
  type DocumentMetadata,
  type DocumentVersion,
} from "./s3";

// Courses module (e-learning)
// Note: PaginatedResult is already exported from chat module
export {
  // Types (excluding PaginatedResult to avoid conflict)
  type Course,
  type CourseCategory,
  type CourseDifficulty,
  type CourseStatus,
  type CreateCourseInput,
  type UpdateCourseInput,
  type CourseItem,
  type Module,
  type CreateModuleInput,
  type UpdateModuleInput,
  type ModuleItem,
  type Lesson,
  type CreateLessonInput,
  type UpdateLessonInput,
  type LessonItem,
  type Quiz,
  type CreateQuizInput,
  type UpdateQuizInput,
  type QuizItem,
  type QuizQuestion,
  type CreateQuizQuestionInput,
  type UpdateQuizQuestionInput,
  type QuizQuestionItem,
  type QuizWithQuestions,
  type UserCourseProgress,
  type CreateUserCourseProgressInput,
  type UserCourseProgressItem,
  type UserModuleProgress,
  type CreateUserModuleProgressInput,
  type UserModuleProgressItem,
  type UserLessonProgress,
  type UserLessonProgressItem,
  type QuizAttempt,
  type CreateQuizAttemptInput,
  type QuizAttemptItem,
  type ProgressStatus,
  type CourseWithModules,
  type ModuleWithLessons,
  type FullCourse,
  type CourseProgressSummary,
  // Course operations
  createCourse,
  getCourse,
  listCourses,
  updateCourse,
  deleteCourse,
  incrementModuleCount,
  publishCourse,
  archiveCourse,
  // Module operations
  createModule,
  getModule,
  listModules,
  updateModule,
  deleteModule,
  incrementLessonCount,
  // Lesson operations
  createLesson,
  getLesson,
  listLessons,
  updateLesson,
  deleteLesson,
  // Quiz operations
  createQuiz,
  getQuiz,
  getQuizForModule,
  updateQuiz,
  deleteQuiz,
  createQuizQuestion,
  batchCreateQuizQuestions,
  listQuizQuestions,
  updateQuizQuestion,
  deleteQuizQuestion,
  getQuizWithQuestions,
  incrementQuestionCount,
  // Progress operations
  enrollInCourse,
  getCourseProgress,
  listUserCourseProgress,
  updateCourseProgress,
  startModule,
  getModuleProgress,
  listUserModuleProgress,
  updateModuleProgress,
  updateLessonProgress,
  getLessonProgress,
  recordQuizAttempt,
  listQuizAttempts,
  getBestQuizAttempt,
} from "./courses";

// Sales Orders module
// Note: PaginatedResult is already exported from chat module
export {
  // Types (excluding PaginatedResult to avoid conflict)
  type Order,
  type OrderStatus,
  type SourceType,
  type ActivityAction,
  type MetricType,
  type ConfidenceField,
  type OrderItem,
  type ExtractedOrderData,
  type ValidationIssue,
  type ValidationResult,
  type ProcessingMetrics,
  type CreateOrderInput,
  type UpdateOrderInput,
  type OrderActivity,
  type CreateActivityInput,
  type OrderMetrics,
  type OrderCustomer,
  type Product,
  // Order operations
  createOrder,
  getOrder,
  updateOrder,
  deleteOrder,
  listOrdersByStatus,
  listOrdersByEntity,
  listOrdersByEntityAndStatus,
  listAllOrders,
  getOrderCountByStatus,
  getOrderCountByEntity,
  getRecentOrders,
  searchOrders,
  // Activity operations
  logActivity,
  getOrderActivity,
  getRecentActivity,
  // Metrics operations
  updateMetrics,
  getMetrics,
  getMetricsRange,
  getTodayMetrics,
  getWeekMetrics,
  getMonthMetrics,
  aggregateMetrics,
  // Utilities
  generateOrderId,
  generateActivityId,
  calculateOverallConfidence,
  getTTL,
  formatOrderNumber,
  validateOrderData,
  calculateTimeSaved,
} from "./sales-orders";

// Customer Lifecycle module
export {
  // Types
  type Lead,
  type CreateLeadInput,
  type UpdateLeadInput,
  type Customer,
  type CreateCustomerInput,
  type UpdateCustomerInput,
  type Interaction,
  type CreateInteractionInput,
  type Purchase,
  type CreatePurchaseInput,
  type Campaign,
  type CreateCampaignInput,
  type UpdateCampaignInput,
  type AIRecommendation,
  type CreateAIRecommendationInput,
  type UpdateAIRecommendationInput,
  // Enums
  LeadSource,
  LeadStatus,
  LeadPriority,
  CustomerStage,
  CustomerSegment,
  InteractionType,
  InteractionChannel,
  Sentiment,
  PaymentMethod,
  CampaignType,
  CampaignStatus,
  TargetType,
  RecommendationType,
  RecommendationPriority,
  RecommendationStatus,
  // Enum helpers
  LEAD_SOURCES,
  LEAD_STATUSES,
  LEAD_PRIORITIES,
  CUSTOMER_STAGES,
  CUSTOMER_SEGMENTS,
  INTERACTION_TYPES,
  INTERACTION_CHANNELS,
  SENTIMENTS,
  PAYMENT_METHODS,
  CAMPAIGN_TYPES,
  CAMPAIGN_STATUSES,
  TARGET_TYPES,
  RECOMMENDATION_TYPES,
  RECOMMENDATION_PRIORITIES,
  RECOMMENDATION_STATUSES,
  // Lead operations
  createLead,
  getLeadById,
  getAllLeads,
  getLeadsByEntity,
  getLeadsByPriority,
  getLeadsByStatus,
  updateLead,
  deleteLead,
  getLeadStats,
  // Customer operations
  createCustomer,
  getCustomerById,
  getAllCustomers,
  getCustomersByEntity,
  getCustomersBySegment,
  getAtRiskCustomers,
  updateCustomer,
  deleteCustomer,
  getCustomerStats,
  // Interaction operations
  createInteraction,
  getInteractionsByLeadId,
  getInteractionsByCustomerId,
  getInteractionsByEntity,
  getInteractionsBySentiment,
  // Purchase operations
  createPurchase,
  getPurchasesByCustomerId,
  getPurchasesByEntity,
  getPurchasesByBrand,
  getPurchaseStats,
  // Campaign operations
  createCampaign,
  getCampaignById,
  getAllCampaigns,
  getActiveCampaigns,
  getCampaignsByEntity,
  updateCampaign,
  deleteCampaign,
  getCampaignStats,
  // AI Recommendation operations
  createAIRecommendation,
  getRecommendationsByTargetId,
  getHighConfidenceRecommendations,
  getRecommendationsByEntity,
  getRecommendationsByType,
  updateAIRecommendation,
  getRecommendationStats,
} from "./lifecycle";

// Users module
export {
  // Types
  type User,
  type UserRole,
  type UserMetadata,
  type CreateUserInput,
  type UpdateUserInput,
  // User operations
  createUser,
  getUserById,
  getUserByEmail,
  getAllUsers,
  getUsersByEntity,
  getUsersByRole,
  getActiveUsers,
  updateUser,
  deleteUser,
  updateLastLogin,
  deactivateUser,
  activateUser,
  getUserStats,
} from "./users";

// App Guide module (feature showcase / help carousel)
export {
  // Types
  type GuideIcon,
  type GuideIconColor,
  type GuideSlide,
  type OnePagerSection,
  type AppOnePager,
  type AppGuide,
  type CreateAppGuideInput,
  // Guide operations
  getAppGuide,
  getAppGuides,
  putAppGuide,
  deleteAppGuide,
  appGuideExists,
} from "./guide";

// Risk Radar module (risk-radar app)
export {
  // Types
  type RiskMetric,
  type CreateRiskMetricInput,
  type UpdateRiskMetricInput,
  type RiskMetricItem,
  type RiskAlert,
  type CreateRiskAlertInput,
  type UpdateRiskAlertInput,
  type RiskAlertItem,
  type ProductType,
  type PeriodType,
  type AlertType,
  type AlertSeverity,
  type AlertStatus,
  type RiskSummary,
  type MetricsTrend,
  type AlertStats,
  // Enum arrays
  PRODUCT_TYPES,
  PERIOD_TYPES,
  ALERT_TYPES,
  ALERT_SEVERITIES,
  ALERT_STATUSES,
  // Metric operations
  upsertRiskMetric,
  getRiskMetric,
  listRiskMetricsByEntity,
  listRiskMetricsByPeriod,
  listRiskMetricsByProduct,
  updateRiskMetric,
  deleteRiskMetric,
  batchCreateRiskMetrics,
  // Alert operations
  createRiskAlert,
  getRiskAlert,
  listRiskAlertsByEntity,
  listRiskAlertsByStatus,
  listRiskAlertsBySeverity,
  listOpenRiskAlerts,
  updateRiskAlert,
  acknowledgeRiskAlert,
  resolveRiskAlert,
  dismissRiskAlert,
  deleteRiskAlert,
  getRiskAlertStats,
  batchCreateRiskAlerts,
  // Utilities
  generateMetricId,
  generateAlertId,
} from "./risk";

// Data Sync module (data-sync app)
export {
  // Types
  type SystemType,
  type ConnectionStatus,
  type SystemConfig,
  type SyncSystem,
  type CreateSyncSystemInput,
  type UpdateSyncSystemInput,
  type SyncSystemItem,
  type SyncMetrics,
  type CreateSyncMetricsInput,
  type SyncMetricsItem,
  type SystemStatusSummary,
  type SyncSummary,
  type DataFlow,
  // Enum arrays
  SYSTEM_TYPES,
  CONNECTION_STATUSES,
  // System operations
  createSyncSystem,
  getSyncSystem,
  listSyncSystems,
  updateSyncSystem,
  deleteSyncSystem,
  batchCreateSyncSystems,
  getSystemStatusSummary,
  // Metrics operations
  upsertSyncMetrics,
  getSyncMetrics,
  listSyncMetrics,
  getGlobalMetrics,
  getTodayGlobalMetrics,
  deleteOldMetrics,
  // Utilities (renamed to avoid conflict with risk module)
  generateMetricId as generateSyncMetricId,
  generateSystemId,
  getTodayDate,
  getCurrentHour,
} from "./sync";

// Promotions module (promotion-control app)
export {
  // Types
  type Promotion,
  type PromotionStatus,
  type PromotionType,
  type DiscountType,
  type PromotionCustomerSegment,
  type SalesChannel,
  type CreatePromotionInput,
  type UpdatePromotionInput,
  type PromotionConflict,
  type ConflictType,
  type ConflictSeverity,
  type ConflictDetectionResult,
  type PromotionStats,
  // Promotion operations
  createPromotion,
  getPromotion,
  updatePromotion,
  deletePromotion,
  listAllPromotions,
  listPromotionsByEntity,
  listPromotionsByStatus,
  getActivePromotions,
  getPromotionsInDateRange,
  searchPromotions,
  getPromotionStats,
  clonePromotion,
  // Conflict detection
  detectConflicts,
  checkConflictsForPromotion,
  validatePromotionRules,
  // Utilities
  generatePromotionId,
  generateConflictId,
  dateRangesOverlap,
  getOverlapPeriod,
  isPromotionActive,
  getEffectiveStatus,
  formatPromotionDiscount,
  getDaysUntil,
  getPromotionDuration,
  sortPromotionsByPriority,
} from "./promotions";
